name: Build and Release

on:
  push:
    tags:
      - 'v*'
  repository_dispatch:
    types: [release-v*]

jobs:
  build:
    name: Build ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact_name: run-this
            asset_name: run-this-${{ github.event_name == 'push' && github.ref_name || format('v{0}', github.event.client_payload.version) }}-linux-x86_64.tar.gz
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            artifact_name: run-this
            asset_name: run-this-${{ github.event_name == 'push' && github.ref_name || format('v{0}', github.event.client_payload.version) }}-linux-aarch64.tar.gz
          - os: macos-latest
            target: x86_64-apple-darwin
            artifact_name: run-this
            asset_name: run-this-${{ github.event_name == 'push' && github.ref_name || format('v{0}', github.event.client_payload.version) }}-macos-x86_64.tar.gz
          - os: macos-latest
            target: aarch64-apple-darwin
            artifact_name: run-this
            asset_name: run-this-${{ github.event_name == 'push' && github.ref_name || format('v{0}', github.event.client_payload.version) }}-macos-aarch64.tar.gz
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            artifact_name: run-this.exe
            asset_name: run-this-${{ github.event_name == 'push' && github.ref_name || format('v{0}', github.event.client_payload.version) }}-windows-x86_64.zip

    steps:
      - uses: actions/checkout@v3

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true

      - name: Install cross-compilation tools
        if: contains(matrix.target, 'aarch64-unknown-linux-gnu')
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target ${{ matrix.target }}
          use-cross: ${{ contains(matrix.target, 'aarch64-unknown-linux-gnu') }}

      - name: Package (Unix)
        if: runner.os != 'Windows'
        run: |
          cd target/${{ matrix.target }}/release
          tar czvf ../../../${{ matrix.asset_name }} ${{ matrix.artifact_name }}
          cd -

      - name: Package (Windows)
        if: runner.os == 'Windows'
        run: |
          cd target/${{ matrix.target }}/release
          7z a ../../../${{ matrix.asset_name }} ${{ matrix.artifact_name }}
          cd -

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.asset_name }}
          path: ${{ matrix.asset_name }}

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set release tag
        id: set_tag
        run: |
          if [ "${{ github.event_name }}" == "push" ]; then
            echo "tag=${{ github.ref_name }}" >> $GITHUB_OUTPUT
          else
            echo "tag=v${{ github.event.client_payload.version }}" >> $GITHUB_OUTPUT
          fi
          echo "Release tag: ${{ github.event_name == 'push' && github.ref_name || format('v{0}', github.event.client_payload.version) }}"

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true

      - name: List files
        run: ls -la

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: run-this-${{ steps.set_tag.outputs.tag }}-*
          tag_name: ${{ steps.set_tag.outputs.tag }}
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 